- fixed more `AttributeError: 'ArrowStringArray' object has no attribute 'item'` errors - adjusted how the dataset that is used to build the grid segmentations is chosen (because before it was possible to choose a dataset that was shorter than the others)