Adjust crop_index assignment for TFE grid (#1263)
* - moved `add_crop_index` to be before the filtering step
- adjusted filtering in `get_dataframe_for_dynamics_workflows` when using "tracked" crop_pattern to only use tracks that are considered acceptable for classic analyses

* - adjustment to dataframe column naming for  `get_dataframe_for_dynamics_workflows`

* - fixed bug that showed up `grid_df.dataset.unique().item()` stopped working (AttributeError: `'ArrowStringArray' object has no attribute 'item'`)
- did some column name spring cleaning

* - added explicit arguments for `get_dataframe_for_dynamics_workflows` since it had changed recently

* - fixed more `AttributeError: 'ArrowStringArray' object has no attribute 'item'` errors
- adjusted how the dataset that is used to build the grid segmentations is chosen (because before it was possible to choose a dataset that was shorter than the others)

* - replaced "track_duration" with `ColumnName.TRACK_LENGTH`
- made application of the `is_included` filter for crop_pattern=tracked happen regardless of if the minimum_track_length was set